# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# AIOS CodeRabbit Configuration
# Story: COLLAB-1, 12.11
# Created: 2025-12-30
# Updated: 2026-02-06 (QA Gate for Squads)
#
# CodeRabbit provides AI-powered code review for pull requests
# Documentation: https://docs.coderabbit.ai/getting-started/yaml-configuration

language: "en-US"
tone_instructions: |
  Act as a strict but constructive Quality Assurance reviewer.
  Flag security issues, bugs, and anti-patterns with high priority.
  Enforce AIOS coding standards (ES2022, single quotes, 2-space indent, absolute imports).
  Be direct about blocking issues. Praise good patterns when found.
early_access: false

reviews:
  # Automatic review settings
  auto_review:
    enabled: true
    base_branches:
      - main
      - develop
      - "feat/*"
      - "fix/*"
      - "release/*"
    drafts: true

  # Review behavior
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  # Path-specific review instructions (array format per schema)
  path_instructions:
    - path: ".aios-core/core/**"
      instructions: |
        CRITICAL PATH: Core framework modules require thorough review.
        Verify error handling is comprehensive with proper try/catch and error context.
        Check for race conditions in orchestration modules (lock-manager, session-state).
        Validate async/await patterns and ensure no unhandled promise rejections.
        Ensure backwards compatibility — core modules are consumed by all agents.
        Check for proper input validation on public API methods.
        Verify test coverage exists for new/modified functions.
        Flag any hardcoded paths, credentials, or environment-specific values.

    - path: ".aios-core/core/orchestration/**"
      instructions: |
        Bob orchestration modules — highest scrutiny required.
        Verify bob-orchestrator.js maintains single-responsibility for workflow dispatch.
        Check lock-manager.js for deadlock prevention and proper cleanup.
        Validate terminal-spawner.js handles all platforms (Unix shell, Windows fallback).
        Ensure workflow-executor.js callback lifecycle is correct (onStart, onComplete, onError).
        Check session-state.js for thread-safety and state corruption prevention.
        Verify message-formatter.js output is consistent across all message types.

    - path: ".aios-core/development/agents/**"
      instructions: |
        Verify agent follows AIOS agent YAML structure (persona_profile, commands, dependencies).
        Check that persona_profile includes archetype, communication style, and greeting_levels.
        Validate all commands listed have corresponding task dependencies.
        Ensure agent has proper visibility metadata for commands.
        Check for security: no hardcoded credentials or sensitive data.

    - path: ".aios-core/development/tasks/**"
      instructions: |
        Verify task follows AIOS task format with clear elicitation points.
        Check that deliverables are well-defined.
        Validate any referenced dependencies exist in the codebase.
        Ensure task has proper error handling guidance.

    - path: ".aios-core/development/workflows/**"
      instructions: |
        Verify workflow YAML structure is valid.
        Check step ordering and dependencies make logical sense.
        Validate referenced agents and tasks exist.

    - path: ".aios-core/product/templates/**"
      instructions: |
        Ensure template follows AIOS template conventions.
        Check placeholder syntax is consistent.
        Validate template produces valid output.

    - path: "squads/**"
      instructions: |
        Squad expansion packs — verify structure follows AIOS squad conventions.
        Check that all agent references are valid.
        Validate squad config and dependencies.
        Ensure no conflicts with core agents or other squads.

    - path: ".github/**"
      instructions: |
        Review for security implications.
        Check for proper secret handling (no hardcoded tokens/keys).
        Validate workflow syntax.
        Ensure consistent with existing CI patterns.
        Check that workflow permissions follow least-privilege principle.

    - path: "**/*.js"
      instructions: |
        QA Checklist:
        - async/await best practices (no floating promises)
        - Error handling with proper context (try/catch, error messages)
        - No console.log in production code (use logger)
        - No hardcoded credentials or secrets
        - AIOS coding standards (ES2022, single quotes, 2-space indent)
        - Absolute imports only (no relative paths like ../)

    - path: "**/*.ts"
      instructions: |
        QA Checklist:
        - TypeScript types properly defined (no 'any')
        - Exports properly typed with interfaces
        - Props interfaces defined for all components
        - Absolute imports only (no relative paths like ../)

    - path: "**/*.tsx"
      instructions: |
        QA Checklist:
        - Component has Props interface
        - No inline styles (use CSS modules or Tailwind)
        - Proper key props in lists
        - No 'any' types
        - Accessibility: alt text, aria labels where needed
        - Absolute imports only

    - path: "**/*.test.*"
      instructions: |
        Verify test coverage is meaningful (not just snapshot tests).
        Check edge cases are covered.
        Ensure test descriptions are clear and follow Given/When/Then or similar pattern.
        Validate mocks are properly cleaned up.

# Chat settings
chat:
  auto_reply: true
